name: CI

env:
  PROJECT_DIR: WorkingTitle
  PROJECT_NAME: WorkingTitle
  USE_ODIN: true
  ODIN_REPO: EuleMitKeule/odin-inspector-3.1.6.1
  GH_PAT: ${{ secrets.GH_PAT }}
  SONAR_PROJECT_KEY: EuleMitKeule_github-gameoff-2022
  SONAR_PROJECT_NAME: github-gameoff-2022
  SONAR_PROJECT_ORGANIZATION: eule

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:

  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.release-version }}
      newVersion: ${{ steps.version.outputs.new-release-published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calculate version
        uses: docker://ghcr.io/codfish/semantic-release-action:latest
        id: version
        with:
          tag_format: 'v${version}'
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    needs: version
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.12f1-base-1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Checkout odin-inspector
        uses: actions/checkout@v3
        with:
           repository: ${{ env.ODIN_REPO }}
           path: odin/
           ref: master
           token: ${{ env.GH_PAT }}
      
      - name: Move odin-inspector
        run: |
          cp -r odin/* ${{ env.PROJECT_DIR }}
          rm -r odin
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_DIR }}/Library
          key: Library-${{ env.PROJECT_DIR }}-TargetPlatform
          restore-keys: |
            Library-${{ env.PROJECT_DIR }}-
            Library-

      - name: Activate license
        run: unity-editor -nographics -logFile /dev/stdout -batchmode -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -quit

      - name: Run editor Tests
        run: unity-editor -nographics -logFile /dev/stdout -projectPath ${{ env.PROJECT_DIR }} -runTests -testPlatform editmode -testResults Tests/editmode-results.xml -enableCodeCoverage -coverageResultsPath Tests -debugCodeOptimization 
        timeout-minutes: 20
        
      - name: Run play Tests
        run: unity-editor -nographics -logFile /dev/stdout -projectPath ${{ env.PROJECT_DIR }} -runTests -testPlatform playmode -testResults Tests/playmode-results.xml -enableCodeCoverage -coverageResultsPath Tests -debugCodeOptimization 
        timeout-minutes: 20

      - name: Store results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: Tests

      - uses: MirageNet/nunit-reporter@v1.1.0
        if: always()
        with:
          path: Tests/*.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

  sonar:
    name: SonarCloud
    needs: test
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.12f1-base-1.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
          
      - name: Checkout odin-inspector
        uses: actions/checkout@v3
        with:
           repository: ${{ env.ODIN_REPO }}
           path: odin/
           ref: master
           token: ${{ env.GH_PAT }}
      
      - name: Move odin-inspector
        run: |
          cp -r odin/* ${{ env.PROJECT_DIR }}
          rm -r odin

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_DIR }}/Library
          key: Library-${{ env.PROJECT_DIR }}-Sonar

      - name: Activate license
        run: unity-editor -nographics -logFile /dev/stdout -batchmode -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -quit

      - name: Generate Solution
        run: unity-editor -nographics -logFile /dev/stdout -projectPath ${{ env.PROJECT_DIR }} -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install SonarScanner .NET
        run: dotnet tool install --tool-path . dotnet-sonarscanner

      - name: Download test results
        id: test-results
        uses: actions/download-artifact@v3
        with:
          name: Test Results
          path: Tests

      - name: Print files
        run: |
          ls -la
          ls -la ${{ env.PROJECT_DIR }}
          ls -la Tests

      - name: SonarCloud Scan
        env:
          FRAMEWORK_PATH: /opt/unity/Editor/Data/MonoBleedingEdge/bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./dotnet-sonarscanner begin \
          /k:${{ env.SONAR_PROJECT_KEY }} \
          /n:${{ env.SONAR_PROJECT_NAME }} \
          /o:${{ env.SONAR_PROJECT_ORGANIZATION }} \
          /d:sonar.host.url=https://sonarcloud.io \
          /d:sonar.login=${{ secrets.SONAR_TOKEN }} \
          /d:sonar.exclusions=**/Assets/Plugins/** \
          /d:sonar.cs.nunit.reportsPaths=Tests/editmode-results.xml,Tests/playmode-results.xml \
          /d:sonar.cs.opencover.reportsPaths=Tests/${{ env.PROJECT_NAME }}-opencov/EditMode/TestCoverageResults_0000.xml,Tests/${{ env.PROJECT_NAME }}-opencov/PlayMode/TestCoverageResults_0000.xml
          dotnet build ${{ env.PROJECT_DIR }}/${{ env.PROJECT_NAME }}.sln
          ./dotnet-sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: version
    strategy:
      matrix:
        buildTarget: ["StandaloneWindows64", "StandaloneOSX", "StandaloneLinux64", "WebGL"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Checkout odin-inspector
        uses: actions/checkout@v3
        with:
           repository: ${{ env.ODIN_REPO }}
           path: odin/
           ref: master
           token: ${{ env.GH_PAT }}
      
      - name: Move odin-inspector
        run: |
          cp -r odin/* ${{ env.PROJECT_DIR }}
          rm -r odin
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_DIR }}/Library
          key: Library-${{ env.PROJECT_DIR }}-TargetPlatform
          restore-keys: |
            Library-${{ env.PROJECT_DIR }}-
            Library-

      - name: Build ${{ matrix.buildTarget }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.buildTarget }}
          projectPath: ${{ env.PROJECT_DIR }}
          buildName: ${{ env.PROJECT_NAME }}-${{ needs.version.outputs.version }}
          buildsPath: ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}
          versioning: Custom
          version: ${{ needs.version.outputs.version }}

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}
      
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.version.outputs.newVersion == 'true' }}
    outputs:
      releaseCreated: ${{ steps.release.outputs.new-release-published }}
      uploadUrl: ${{ steps.getUploadUrl.outputs.uploadUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        if: ${{ github.event_name == 'push' }}
        uses: docker://ghcr.io/codfish/semantic-release-action:latest
        id: release
        with:
          tag_format: 'v${version}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get upload URL
        if: |
          ${{ steps.release.outputs.new-release-published == 'true' }} &&
          ${{ github.event_name == 'push' }}
        id: getUploadUrl
        run: |
          echo "getting upload url for release ${{ steps.release.outputs.version }} with tag v${{ steps.release.outputs.release-version }}"
          uploadUrl=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.release.outputs.release-version }} | jq -r '.upload_url')
          echo uploadUrl=$uploadUrl >> $GITHUB_OUTPUT

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releaseCreated == 'true' }}
    strategy:
      matrix:
        buildTarget: ["StandaloneWindows64", "StandaloneOSX", "StandaloneLinux64", "WebGL"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: Build
          path: ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}

      - name: Zip build
        run: |
          cd ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}
          zip -r ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}.zip ./*
          mv ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}.zip ../

      - name: Upload build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.uploadUrl }}
          asset_path: ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}.zip
          asset_name: ${{ env.PROJECT_NAME }}-${{ matrix.buildTarget }}-${{ needs.version.outputs.version }}
          asset_content_type: application/zip
