name: Test PR

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          
      - name: Checkout odin-inspector
        uses: actions/checkout@v3
        with:
           repository: EuleMitKeule/odin-inspector-3.1.6.1
           path: odin/
           ref: master
           token: ${{ secrets.GH_PAT }}
      
      - name: Move odin-inspector
        run: |
          cp -r odin/* WorkingTitle/
          rm -r odin
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: WorkingTitle/Library
          key: Library-WorkingTitle-TargetPlatform
          restore-keys: |
            Library-WorkingTitle-
            Library-

      - name: Run tests
        id: run-tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: WorkingTitle/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageOptions generateBadgeReport;assemblyFilters:+WorkingTitle.Unity,+WorkingTitle.Lib -coverageResultsPath coverage

      - name: Store results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

      - name: Store coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Code coverage
          path: ./WorkingTitle/coverage